# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20170523_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritecontent',
            name='content',
        ),
        migrations.RemoveField(
            model_name='favoritecontent',
            name='user',
        ),
        migrations.DeleteModel(
            name='FavoriteContent',
        ),
    ]
