# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20170523_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemId', models.CharField(max_length=100, verbose_name='Id del Item')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Content')),
            ],
            options={
                'verbose_name': 'Ítem de lista',
                'verbose_name_plural': 'Ítems de lista',
            },
        ),
    ]
