# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_listitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listitem',
            old_name='itemId',
            new_name='item_id',
        ),
    ]
