# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 05:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20170603_1613'),
        ('content', '0006_auto_20170603_0706'),
    ]

    operations = [
    ]
