# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_merge_20170604_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.Content'),
        ),
    ]
