# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20170604_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='item_name',
            field=models.CharField(default='', max_length=500, verbose_name='Nombre del item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listitem',
            name='item_type',
            field=models.CharField(default='movie', max_length=50, verbose_name='Tipo de item'),
            preserve_default=False,
        ),
    ]
