# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20170604_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='date',
        ),
        migrations.AlterField(
            model_name='content',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='content.Section'),
        ),
        migrations.AlterField(
            model_name='content',
            name='tags',
            field=models.ManyToManyField(blank=True, db_table='ContentTag', related_name='content', to='content.Tag', verbose_name='Tags'),
        ),
    ]
