# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20170606_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='last_modification_user',
        ),
    ]
