# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_remove_content_last_modification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.CharField(max_length=50, verbose_name='Texto'),
        ),
    ]
