file_list = [
    'Actividad.TPS',
    'ACUMULA.TPS',
    'Agroquim.Tps',
    # 'ANEXO.TPS',
    'Banc.Tps',
    'BANCOS.TPS',
    'Cajas.Tps',
    'Categorias.tps',
    # 'Chofer.Tps',
    # 'Clering.Tps',
    # 'Cod_Comprob.TPS',
    # 'Config.TPS',
    # 'CONPAGO.TPS',
    # 'Consocia.tps',
    # 'Contador.Tps',
    'Contrat.Tps',
    'Cultivo.Tps',
    'Deposito_Stock.tps',
    # 'Distancia.Tps',
    # 'Feriados.Tps',
    'Fertiliz.Tps',
    'For_Fer.Tps',
    'Formula.Tps',
    # 'Grado.TPS',
    'Grupos.tps',
    # 'Impuesto.tps',
    # 'IMPUTACI.TPS',
    'IMPUTACI.TPS',
    # 'Indices.Tps',
    'Laboreo.Tps',
    'Lineas.Tps',
    # 'Mot_Deb.TPS',
    # 'MOTIPAGO.TPS',
    # 'Motivo.Tps',
    'Motivos.tps',
    'Movim.tps',
    # 'MS.Tps',
    # 'MultiEmpresa.TPS',
    # 'Param.TPS',
    # 'Periodo.tps',
    # 'Pesadas.tps',
    # 'Pes_Ite.tps',
    # 'Porc_Sueldos.TPS',
    # 'PRINTOPA.TPS',
    'Provincias.Tps',
    'Localidad.Tps',
    # 'Rel_Holistor.TPS',
    'Respons.Tps',
    'RETENCIO.TPS',
    'RET_IB.TPS',
    'Rodados.Tps',
    'Rubros.Tps',
    'Tambos.tps',
    'Tanque.Tps',
    'TIPOPROV.TPS',
    'Titular.Tps',
    'Transp.tps',
    # 'UGENERAD.TPS',
    'Acoplado.tps',
    # 'Acredita.TPS',
    # 'Acred_Pend.TPS',
    'Bolsas.Tps',
    'Camion.tps',
    'Campana.Tps',
    # 'Sector.Tps',
    # 'SubSecto.Tps',
    'Campos.TPS',
    # 'Cli.Tps',
    'Cli.TPS',
    'PROCTCTE.TPS',
    # 'Provedor.Tps',
    # 'Carga.tps',
    # 'CargaOC.Tps',
    # 'CCarga.tps',
    'Recibos.TPS',
    'ORD_PAGO.TPS',
    # 'CheqPag.TPS',
    # 'CHEQPROP.TPS',
    # 'CheqRec.TPS',
    # 'Cheques.Tps',
    'Cheques.Tps',
    # 'CheqAnt.Tps',
    # 'Cobrados.TPS',
    # 'CREDITOS.TPS',
    # 'CTA_CTE.TPS',
    # 'CtePro.TPS',
    # 'CteProCC.TPS',
    # 'CVenta.tps',
    # 'DEBITOS.TPS',
    # 'DEPOSITO.TPS',
    'Destino.Tps',
    'Rodeo.tps',
    'Gan_Car.tps',
    'GF.Tps',
    # 'GG.Tps',
    # 'Giros.TPS',
    # 'GLIbroBa.TPS',
    # 'GRecibo.TPS',
    # 'GUARETEN.TPS',
    # 'GUARETENIB.TPS',
    # 'GUARETENIVA.TPS',
    # 'Humedad.Tps',
    # 'InterDep.TPS',
    'Potreros.Tps',
    'Producto.Tps',
    # 'Items.Tps',
    'Items.Tps',
    # 'LIBROBA.TPS',
    # 'MaeChe.Tps',
    # 'MaeCli.Tps',
    # 'Maquina.Tps',
    'Maquina.Tps',
    # 'MENSUAL.TPS',
    # 'Montos_Para_Girar.TPS',
    'Mov_Camp.Tps',
    'Tractor.Tps',
    'Mov_Cons.Tps',
    'Silos.Tps',
    'Tractori.Tps',
    'Mov_Cose.Tps',
    'Mov_Hora.tps',
    'Mov_Leche.TPS',
    # 'Mov_Potr.tps',
    'Mov_Prod.tps',
    'Mov_Silos.tps',
    'Mov_Suple.Tps',
    'Mov_Trac.tps',
    'Mov_Trans.tps',
    'MovGan.tps',
    'Movimpu.tps',
    # 'NImpVta.Tps',
    # 'Nov_Agro.Tps',
    # 'Nov_Camp.tps',
    # 'Nov_Cons.Tps',
    # 'Nov_Cose.Tps',
    # 'Nov_Fert.Tps',
    # 'Nov_Fin.Tps',
    # 'Nov_Ganado.tps',
    # 'Nov_Gran.TPS',
    # 'Nov_Hora.tps',
    # 'Nov_Lluv.Tps',
    # 'Nov_Maqu.Tps',
    # 'Nov_Plan.tps',
    # 'Nov_Prod.tps',
    # 'Nov_Roll.Tps',
    # 'Nov_Serv.TPS',
    # 'Nov_Siem.Tps',
    # 'Nov_Suel.TPS',
    # 'Nov_Suple.Tps',
    # 'Nov_Transp.TPS',
    # 'NovCheRec.TPS',
    # 'NOVCHPRO.TPS',
    # 'NOVCTCTE.TPS',
    # 'NOVEDAD.TPS',
    # 'Novedad_Ganado.tps',
    # 'Noventas.TPS',
    # 'NovImp.tps',
    # 'NovImpGran.TPS',
    # 'NovImpServ.TPS',
    # 'NovImpTransp.TPS',
    # 'NovImpu.TPS',
    # 'NovImpVta.tps',
    # 'NovPref.Tps',
    # 'ObservOP.TPS',
    # 'PAGADOS.TPS',
    'PendCobro.TPS',
    # 'Pendpago.tps',
    'PENDPAGO.TPS',
    # 'PRGASTOS.TPS',
    # 'Pro_Car.Tps',
    # 'Pro_Car_OC.Tps',
    # 'Pro_Ven.Tps',
    # 'RESOPAGO.TPS',
    # 'RET_PROV.TPS',
    # 'StockDep.tps',
    # 'StockSil.Tps',
    # 'Temp_C.TPS',
    # 'Temp_Prod.tps',
    # 'Temp_Sto.Tps',
    # 'TERCEROS.TPS',
    # 'TMPCajas.TPS',
    # 'VCarga.tps',
    # 'VCta_Cte.TPS',
    # 'Ven_Car.tps',
    'Ventas.TPS'
]
