# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 04:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Nombre de usuario')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Correo electrónico')),
                ('state', models.CharField(choices=[('Pendiente de Confirmación', 'Pendiente de Confirmación'), ('Confirmado', 'Confirmado'), ('Baneado Temporalmente', 'Baneado Temporalmente'), ('Baneado', 'Baneado')], default='Confirmado', max_length=100, verbose_name='Estado')),
                ('temporary_ban_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de fin de baneo temporal')),
                ('activation_key', models.CharField(blank=True, max_length=500, null=True)),
                ('key_expiration_date', models.DateTimeField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('date_of_birth', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='Foto de perfil')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500, verbose_name='Comentario')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='complaints',
            field=models.ManyToManyField(related_name='complaints', through='home.Complaint', to='content.Content'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='following',
            field=models.ManyToManyField(blank=True, db_table='Followers', related_name='seguidores', to=settings.AUTH_USER_MODEL, verbose_name='Siguiendo'),
        ),
    ]
