# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ban_count',
            field=models.IntegerField(default=0, verbose_name='Cantidad de baneos'),
        ),
    ]
