# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 03:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170523_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritecontent',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Content'),
        ),
        migrations.AlterField(
            model_name='favoritecontent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
