# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170524_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=models.CharField(choices=[('Pendiente de Confirmación', 'Pendiente de Confirmación'), ('Confirmado', 'Confirmado'), ('Baneado Temporalmente', 'Baneado Temporalmente'), ('Baneado Permanentemente', 'Baneado Permanentemente')], default='Confirmado', max_length=100, verbose_name='Estado'),
        ),
    ]
