# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 00:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170603_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='following',
            field=models.ManyToManyField(blank=True, db_table='Followers', related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='Siguiendo'),
        ),
    ]
